"""store all prices, not only discounts

Revision ID: 080d12695e10
Revises: b3f41c7d2e90
Create Date: 2026-10-02 13:20:32.101366+02:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "080d12695e10"
down_revision: str | None = "b3f41c7d2e90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


PROMO_VALUES = ("discount", "loyalty", "multibuy", "other", "none")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "current_price",
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("sale_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("regular_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("discount_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("discount_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("unit_price_base", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "promo_type",
            sa.Enum(
                "discount",
                "loyalty",
                "multibuy",
                "other",
                "none",
                name="promotype",
                native_enum=False,
                length=16,
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column("is_discount", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_single_day", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("availability", sa.String(length=96), nullable=True),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_current_price_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
            name=op.f("fk_current_price_store_id_store"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("store_id", "product_id", name=op.f("pk_current_price")),
    )
    op.create_index(
        "ix_current_price_discounts",
        "current_price",
        ["store_id"],
        unique=False,
        postgresql_where=sa.text("is_discount"),
    )
    op.create_index(
        "ix_current_price_product", "current_price", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_current_price_run_date"), "current_price", ["run_date"], unique=False
    )
    op.create_index(
        "ix_current_price_store_product",
        "current_price",
        ["store_id", "product_id"],
        unique=False,
    )
    op.create_table(
        "daily_store_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("products_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("discounts_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("loyalty_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("single_day_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("changed_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("avg_discount_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("max_discount_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("total_savings", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
            name=op.f("fk_daily_store_stats_store_id_store"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_store_stats")),
        sa.UniqueConstraint("store_id", "run_date", name="daily_store_stats_once_a_day"),
    )
    op.create_index(
        "ix_daily_store_stats_date", "daily_store_stats", ["run_date"], unique=False
    )
    op.create_table(
        "price_change",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("changed_on", sa.Date(), nullable=False),
        sa.Column("sale_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("discount_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("is_discount", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "previous_sale_price", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "previous_discount_price", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_price_change_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
            name=op.f("fk_price_change_store_id_store"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_change")),
        sa.UniqueConstraint(
            "store_id", "product_id", "changed_on", name="price_change_once_a_day"
        ),
    )
    op.create_index(
        op.f("ix_price_change_changed_on"), "price_change", ["changed_on"], unique=False
    )
    op.create_index(
        "ix_price_change_product_date",
        "price_change",
        ["product_id", "changed_on"],
        unique=False,
    )
    op.create_index(
        "ix_price_change_store_date",
        "price_change",
        ["store_id", "changed_on"],
        unique=False,
    )
    allowed = ", ".join(f"'{value}'" for value in PROMO_VALUES)
    op.create_check_constraint(
        "promo_type_valid", "current_price", f"promo_type IN ({allowed})"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_change_store_date", table_name="price_change")
    op.drop_index("ix_price_change_product_date", table_name="price_change")
    op.drop_index(op.f("ix_price_change_changed_on"), table_name="price_change")
    op.drop_table("price_change")
    op.drop_index("ix_daily_store_stats_date", table_name="daily_store_stats")
    op.drop_table("daily_store_stats")
    op.drop_index("ix_current_price_store_product", table_name="current_price")
    op.drop_index(op.f("ix_current_price_run_date"), table_name="current_price")
    op.drop_index("ix_current_price_product", table_name="current_price")
    op.drop_index(
        "ix_current_price_discounts",
        table_name="current_price",
        postgresql_where=sa.text("is_discount"),
    )
    op.drop_table("current_price")
    # ### end Alembic commands ###
