"""store what each user follows

`user_category` врзуваше корисник за категорија. Изборот порасна и веќе не
е само категорија: носи и зборови од називот - вид („инстант"), бренд
(„нескафе"), грамажа („200г"). Врзување за ред во `product_category` не
може да го изрази тоа.

`user_pick` го чува изборот во ИСТИОТ запис како URL-то и колачето
(„kafe~нескафе"), па трите места зборуваат еден јазик и го делат истиот
парсер. Нема врска кон `product_category` намерно: слугот е идентитетот низ
апликацијата, категориите се создаваат од код, а непознат слуг се игнорира
при читање наместо тивко да го смени значењето на изборот.

`user_category` беше празна - моделите за најава постоеја, но никогаш не
беа вклучени.

Revision ID: d52ced27733d
Revises: 080d12695e10
Create Date: 2026-10-04 09:49:57.790424+02:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d52ced27733d"
down_revision: str | None = "080d12695e10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_pick",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pick_key", sa.String(length=200), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_user_pick_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_pick")),
        sa.UniqueConstraint("user_id", "pick_key", name="user_pick_unique"),
    )
    op.create_index(op.f("ix_user_pick_user_id"), "user_pick", ["user_id"], unique=False)
    op.drop_table("user_category")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_category",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_category.id"],
            name=op.f("fk_user_category_category_id_product_category"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_user_category_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "category_id", name=op.f("pk_user_category")),
    )
    op.drop_index(op.f("ix_user_pick_user_id"), table_name="user_pick")
    op.drop_table("user_pick")
    # ### end Alembic commands ###
