"""accounts identified by address alone

Корисничкото име излезе. Адресата е сè: со неа се отвора сметката, се
потврдува со линк, и се влегува - едно поле наместо две.

Колоната останува празнлива наместо да падне, за да постоечките сметки не
се кршат. Името што се гледа на екран се вади од адресата.

Revision ID: bb5b6bba46b5
Revises: 4df9921a3a97
Create Date: 2026-10-05 18:28:43.047197+02:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bb5b6bba46b5"
down_revision: str | None = "4df9921a3a97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "app_user", "username", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "app_user", "username", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    # ### end Alembic commands ###
