"""accounts without a password

Сметката веќе не носи лозинка. Се отвора со корисничко име и адреса, а
влегувањето оди преку линк што стигнува на таа адреса - истиот механизам и
за првата потврда и за секоја следна најава.

`email` е единствена: едно сандаче, една сметка. Може да фали, зашто
сметките направени пред ова ја немаат; таквите не можат да влезат додека не
им се запише адреса (`python -m app.cli vlez`).

`password_hash` станува празнлива наместо да падне: старите сметки не се
кршат, а новите не ја пишуваат. Кога ќе се испразни сосема, колоната може
да се отстрани.

`login_code` е еднократниот код во последниот испратен линк. Се брише при
влегување, па линкот важи еднаш, а нов линк го поништува претходниот.

Revision ID: 4df9921a3a97
Revises: d52ced27733d
Create Date: 2026-10-05 13:11:54.061055+02:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4df9921a3a97"
down_revision: str | None = "d52ced27733d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_user", sa.Column("email", sa.String(length=254), nullable=True))
    op.add_column(
        "app_user",
        sa.Column("email_confirmed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "app_user", sa.Column("login_code", sa.String(length=64), nullable=True)
    )
    op.alter_column(
        "app_user", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_index(op.f("ix_app_user_email"), "app_user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_app_user_email"), table_name="app_user")
    op.alter_column(
        "app_user", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("app_user", "login_code")
    op.drop_column("app_user", "email_confirmed_at")
    op.drop_column("app_user", "email")
    # ### end Alembic commands ###
