"""initial schema

Revision ID: 8ae205c0b9f8
Revises:
Create Date: 2026-10-01 23:16:32.362709+02:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8ae205c0b9f8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chain",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chain")),
    )
    op.create_index(op.f("ix_chain_code"), "chain", ["code"], unique=True)
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_city")),
    )
    op.create_index(op.f("ix_city_slug"), "city", ["slug"], unique=True)
    op.create_table(
        "product_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("default_base_unit", sa.String(length=16), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="100", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["product_category.id"],
            name=op.f("fk_product_category_parent_id_product_category"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_category")),
    )
    op.create_index(
        op.f("ix_product_category_slug"), "product_category", ["slug"], unique=True
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column(
            "follow_all_stores", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
            name=op.f("fk_app_user_city_id_city"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
    )
    op.create_index(op.f("ix_app_user_city_id"), "app_user", ["city_id"], unique=False)
    op.create_index(op.f("ix_app_user_username"), "app_user", ["username"], unique=True)
    op.create_table(
        "category_keyword",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(length=160), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_negative", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_category.id"],
            name=op.f("fk_category_keyword_category_id_product_category"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_keyword")),
        sa.UniqueConstraint("category_id", "keyword", name="category_keyword_unique"),
    )
    op.create_index(
        op.f("ix_category_keyword_category_id"),
        "category_keyword",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        "ix_category_keyword_lookup",
        "category_keyword",
        ["keyword", "is_negative"],
        unique=False,
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("raw_name", sa.Text(), nullable=False),
        sa.Column("raw_description", sa.Text(), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("brand", sa.String(length=160), nullable=True),
        sa.Column("package_value", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("package_unit", sa.String(length=16), nullable=True),
        sa.Column("base_quantity", sa.Numeric(precision=14, scale=5), nullable=True),
        sa.Column("base_unit", sa.String(length=16), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "category_status",
            sa.String(length=16),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("category_matched_keyword", sa.String(length=160), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "package_value IS NULL OR package_value > 0",
            name=op.f("ck_product_package_value_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_category.id"],
            name=op.f("fk_product_category_id_product_category"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chain.id"],
            name=op.f("fk_product_chain_id_chain"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("chain_id", "fingerprint", name="product_chain_fingerprint"),
    )
    op.create_index(op.f("ix_product_brand"), "product", ["brand"], unique=False)
    op.create_index(
        op.f("ix_product_category_id"), "product", ["category_id"], unique=False
    )
    op.create_index(
        "ix_product_category_status",
        "product",
        ["category_id", "category_status"],
        unique=False,
    )
    op.create_index(op.f("ix_product_chain_id"), "product", ["chain_id"], unique=False)
    op.create_table(
        "store",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chain.id"],
            name=op.f("fk_store_chain_id_chain"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
            name=op.f("fk_store_city_id_city"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store")),
        sa.UniqueConstraint("chain_id", "external_id", name="store_chain_external"),
    )
    op.create_index("ix_store_chain_city", "store", ["chain_id", "city_id"], unique=False)
    op.create_index(op.f("ix_store_chain_id"), "store", ["chain_id"], unique=False)
    op.create_index(op.f("ix_store_city_id"), "store", ["city_id"], unique=False)
    op.create_table(
        "pricelist_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("pricelist_date", sa.Date(), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "status", sa.String(length=24), server_default="running", nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rows_discount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rows_skipped", sa.Integer(), server_default="0", nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("error_type", sa.String(length=96), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chain.id"],
            name=op.f("fk_pricelist_run_chain_id_chain"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
            name=op.f("fk_pricelist_run_store_id_store"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricelist_run")),
    )
    op.create_index(
        "ix_pricelist_run_chain_date",
        "pricelist_run",
        ["chain_id", "run_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricelist_run_run_date"), "pricelist_run", ["run_date"], unique=False
    )
    op.create_index(
        op.f("ix_pricelist_run_status"), "pricelist_run", ["status"], unique=False
    )
    op.create_index(
        "ix_pricelist_run_status_date",
        "pricelist_run",
        ["status", "run_date"],
        unique=False,
    )
    op.create_index(
        "ix_pricelist_run_store_date",
        "pricelist_run",
        ["store_id", "run_date"],
        unique=False,
    )
    op.create_table(
        "user_category",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_category.id"],
            name=op.f("fk_user_category_category_id_product_category"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_user_category_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "category_id", name=op.f("pk_user_category")),
    )
    op.create_table(
        "user_store",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
            name=op.f("fk_user_store_store_id_store"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_user_store_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "store_id", name=op.f("pk_user_store")),
    )
    op.create_table(
        "price_row",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("sale_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("regular_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("discount_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("discount_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("unit_price_raw", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("unit_price_base", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "promo_type", sa.String(length=16), server_default="none", nullable=False
        ),
        sa.Column("promo_type_raw", sa.String(length=255), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_single_day", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_discount", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("availability", sa.String(length=96), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_pct IS NULL OR (discount_pct >= 0 AND discount_pct <= 100)",
            name=op.f("ck_price_row_discount_pct_range"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_price_row_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pricelist_run.id"],
            name=op.f("fk_price_row_run_id_pricelist_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
            name=op.f("fk_price_row_store_id_store"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_row")),
    )
    op.create_index(
        "ix_price_row_discounts",
        "price_row",
        ["store_id", "run_date"],
        unique=False,
        postgresql_where=sa.text("is_discount"),
    )
    op.create_index(
        op.f("ix_price_row_is_discount"), "price_row", ["is_discount"], unique=False
    )
    op.create_index(
        "ix_price_row_product_date", "price_row", ["product_id", "run_date"], unique=False
    )
    op.create_index("ix_price_row_run", "price_row", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_row_run", table_name="price_row")
    op.drop_index("ix_price_row_product_date", table_name="price_row")
    op.drop_index(op.f("ix_price_row_is_discount"), table_name="price_row")
    op.drop_index(
        "ix_price_row_discounts",
        table_name="price_row",
        postgresql_where=sa.text("is_discount"),
    )
    op.drop_table("price_row")
    op.drop_table("user_store")
    op.drop_table("user_category")
    op.drop_index("ix_pricelist_run_store_date", table_name="pricelist_run")
    op.drop_index("ix_pricelist_run_status_date", table_name="pricelist_run")
    op.drop_index(op.f("ix_pricelist_run_status"), table_name="pricelist_run")
    op.drop_index(op.f("ix_pricelist_run_run_date"), table_name="pricelist_run")
    op.drop_index("ix_pricelist_run_chain_date", table_name="pricelist_run")
    op.drop_table("pricelist_run")
    op.drop_index(op.f("ix_store_city_id"), table_name="store")
    op.drop_index(op.f("ix_store_chain_id"), table_name="store")
    op.drop_index("ix_store_chain_city", table_name="store")
    op.drop_table("store")
    op.drop_index(op.f("ix_product_chain_id"), table_name="product")
    op.drop_index("ix_product_category_status", table_name="product")
    op.drop_index(op.f("ix_product_category_id"), table_name="product")
    op.drop_index(op.f("ix_product_brand"), table_name="product")
    op.drop_table("product")
    op.drop_index("ix_category_keyword_lookup", table_name="category_keyword")
    op.drop_index(op.f("ix_category_keyword_category_id"), table_name="category_keyword")
    op.drop_table("category_keyword")
    op.drop_index(op.f("ix_app_user_username"), table_name="app_user")
    op.drop_index(op.f("ix_app_user_city_id"), table_name="app_user")
    op.drop_table("app_user")
    op.drop_index(op.f("ix_product_category_slug"), table_name="product_category")
    op.drop_table("product_category")
    op.drop_index(op.f("ix_city_slug"), table_name="city")
    op.drop_table("city")
    op.drop_index(op.f("ix_chain_code"), table_name="chain")
    op.drop_table("chain")
    # ### end Alembic commands ###
